site_name: SPAN SG
# TODO-2025-10-07: site_url vérifié (public, repo personnel)
site_url: https://alexmacapple.github.io/span-sg/
# TODO-2025-10-07: repo_url vérifié
repo_url: https://github.com/Alexmacapple/span-sg
strict: true

theme:
  name: dsfr
  language: fr

plugins:
  - search:
      lang: fr

nav:
  - SPAN (SG): index.md
  - SPAN (services):
    - BGS: modules/bgs.md
    - SAFI: modules/safi.md
    - SIEP: modules/siep.md
    - SIRCOM: modules/sircom.md
    - SNUM: modules/snum.md
    - SRH: modules/srh.md
  - Synthèse: synthese.md
  - Processus: processus.md
  - Guide contributeur: contributing.md
  - Développement local: dev-local.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
