site_name: SPAN SG
# TODO-2025-10-07: site_url vérifié (public, repo personnel)
site_url: https://alexmacapple.github.io/span-sg-repo/
# TODO-2025-10-07: repo_url vérifié
repo_url: https://github.com/Alexmacapple/span-sg-repo
strict: true

theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

plugins:
  - search:
      lang: fr

nav:
  - Accueil: index.md
  - SPAN-SERVICES:
    - BGS: modules/bgs.md
    - SAFI: modules/safi.md
    - SIEP: modules/siep.md
    - SIRCOM: modules/sircom.md
    - SNUM: modules/snum.md
    - SRH: modules/srh.md
  - Synthèse: synthese.md
  - Processus: processus.md
  - Guide contributeur: contributing.md
  - Développement local: dev-local.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
