name: Build SPAN

on:
  push:
    branches: [main, draft]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy-draft:
    if: github.ref == 'refs/heads/draft'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements-dsfr.txt

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Black formatter check
        run: python -m black --check scripts/

      - name: Run Ruff linter
        run: python -m ruff check scripts/

      - name: Install security tools
        run: pip install -r requirements-security.txt

      - name: Run Bandit security linter
        run: |
          echo "=== Bandit Security Analysis ==="
          echo "Analyzing scripts/ and hooks/ for security issues..."
          echo "(Excluding test files to avoid false positives)"
          echo ""

          # Generate JSON report (non-blocking)
          bandit -r scripts/ hooks/ -ll -x scripts/test_*.py,tests/ -f json -o bandit-report.json || true

          # Display summary and fail on HIGH/CRITICAL
          bandit -r scripts/ hooks/ -ll -x scripts/test_*.py,tests/ --format screen

          echo ""
          echo "=== Bandit analysis complete ==="

      - name: Check dependencies vulnerabilities (Safety)
        run: |
          echo "=== Safety CVE Check ==="
          echo "Checking requirements-dsfr.txt for known vulnerabilities..."
          echo ""

          # Generate JSON report (non-blocking)
          safety check -r requirements-dsfr.txt --json > safety-report.json || true

          # Fail if vulnerabilities found
          safety check -r requirements-dsfr.txt

          echo ""
          echo "=== No vulnerabilities found ==="

      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-${{ github.ref_name }}-${{ github.sha }}
          path: |
            bandit-report.json
            safety-report.json
          retention-days: 90

      - name: Run unit tests
        run: python -m pytest scripts/ -v --cov=scripts --cov-report=term-missing

      - name: Run production scripts coverage check (89%+ required)
        run: |
          python -m pytest \
            --cov=scripts \
            --cov-report=term-missing \
            --cov-report=html \
            --cov-fail-under=89 \
            scripts/test_calculate_scores*.py scripts/test_enrich_pdf*.py

      - name: Run hooks coverage check (100% required)
        run: |
          python -m pytest \
            tests/test_hooks_*.py \
            --cov=hooks \
            --cov-config=.coveragerc-hooks \
            --cov-report=term-missing \
            --cov-report=html:htmlcov-hooks \
            --cov-fail-under=100

      - name: Calculate SPAN scores
        run: python scripts/calculate_scores.py

      - name: Build site DSFR
        run: mkdocs build --config-file mkdocs-dsfr.yml --strict

      - name: Verify DSFR theme in build
        run: |
          echo "=== Vérification DSFR ==="
          if grep -q "writer-html5" site/index.html; then
            echo "❌ ERREUR: HTML contient ReadTheDocs au lieu de DSFR!"
            head -20 site/index.html
            exit 1
          elif grep -q "data-fr-scheme" site/index.html; then
            echo "✅ OK: HTML contient DSFR"
            head -5 site/index.html
          else
            echo "⚠️  WARNING: Thème indéterminé"
            head -20 site/index.html
            exit 1
          fi

      - name: Install WeasyPrint system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libpango-1.0-0 \
            libpangoft2-1.0-0 \
            libpangocairo-1.0-0 \
            libcairo2 \
            libffi-dev \
            libgdk-pixbuf2.0-0 \
            libharfbuzz-dev \
            shared-mime-info

      - name: Generate PDF (DSFR)
        env:
          ENABLE_PDF_EXPORT: "1"
        run: |
          mkdir -p exports
          mkdocs build --config-file mkdocs-dsfr-pdf.yml --site-dir pdf-temp

      - name: Enrich PDF metadata
        run: python scripts/enrich_pdf_metadata.py exports/span-sg.pdf

      - name: Install qpdf
        run: |
          sudo apt-get update
          sudo apt-get install -y qpdf

      - name: Validate PDF
        run: |
          qpdf --check exports/span-sg.pdf
          ls -lh exports/span-sg.pdf
          echo "PDF size: $(du -h exports/span-sg.pdf | cut -f1)"

      - name: Upload PDF artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: exports-draft
          path: exports/

      - name: DEBUG INTENSIF - Vérifier site/ juste avant copie
        run: |
          echo "=== CONTENU DE site/ JUSTE AVANT COPIE ==="
          ls -la site/ | head -20
          echo ""
          echo "=== site/index.html (premières 20 lignes) ==="
          head -20 site/index.html
          echo ""
          echo "=== Vérification DSFR dans site/index.html ==="
          if grep -q "data-fr-scheme" site/index.html; then
            echo "✅ DSFR présent dans site/index.html"
          else
            echo "❌ DSFR ABSENT de site/index.html!"
            exit 1
          fi

      - name: Deploy draft to GitHub Pages (Git push direct)
        run: |
          # Configuration Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone gh-pages
          git clone --depth=1 --branch=gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages-repo

          # Supprimer ancien draft et copier nouveau
          rm -rf gh-pages-repo/draft
          mkdir -p gh-pages-repo/draft

          echo "=== COPIE site/ vers gh-pages-repo/draft/ ==="
          cp -rv site/* gh-pages-repo/draft/ | head -10

          echo ""
          echo "=== VÉRIFICATION gh-pages-repo/draft/index.html APRÈS COPIE ==="
          head -10 gh-pages-repo/draft/index.html

          # Push
          cd gh-pages-repo
          git add .
          git commit -m "Deploy draft from ${{ github.sha }}" || echo "No changes"
          git push origin gh-pages

  build-and-deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements-dsfr.txt

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Black formatter check
        run: python -m black --check scripts/

      - name: Run Ruff linter
        run: python -m ruff check scripts/

      - name: Install security tools
        run: pip install -r requirements-security.txt

      - name: Run Bandit security linter
        run: |
          echo "=== Bandit Security Analysis ==="
          echo "Analyzing scripts/ and hooks/ for security issues..."
          echo "(Excluding test files to avoid false positives)"
          echo ""

          # Generate JSON report (non-blocking)
          bandit -r scripts/ hooks/ -ll -x scripts/test_*.py,tests/ -f json -o bandit-report.json || true

          # Display summary and fail on HIGH/CRITICAL
          bandit -r scripts/ hooks/ -ll -x scripts/test_*.py,tests/ --format screen

          echo ""
          echo "=== Bandit analysis complete ==="

      - name: Check dependencies vulnerabilities (Safety)
        run: |
          echo "=== Safety CVE Check ==="
          echo "Checking requirements-dsfr.txt for known vulnerabilities..."
          echo ""

          # Generate JSON report (non-blocking)
          safety check -r requirements-dsfr.txt --json > safety-report.json || true

          # Fail if vulnerabilities found
          safety check -r requirements-dsfr.txt

          echo ""
          echo "=== No vulnerabilities found ==="

      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-${{ github.ref_name }}-${{ github.sha }}
          path: |
            bandit-report.json
            safety-report.json
          retention-days: 90

      - name: Run unit tests
        run: python -m pytest scripts/ -v --cov=scripts --cov-report=term-missing

      - name: Run production scripts coverage check (89%+ required)
        run: |
          python -m pytest \
            --cov=scripts \
            --cov-report=term-missing \
            --cov-report=html \
            --cov-fail-under=89 \
            scripts/test_calculate_scores*.py scripts/test_enrich_pdf*.py

      - name: Run hooks coverage check (100% required)
        run: |
          python -m pytest \
            tests/test_hooks_*.py \
            --cov=hooks \
            --cov-config=.coveragerc-hooks \
            --cov-report=term-missing \
            --cov-report=html:htmlcov-hooks \
            --cov-fail-under=100

      - name: Calculate SPAN scores
        run: python scripts/calculate_scores.py

      - name: Build site DSFR
        run: mkdocs build --config-file mkdocs-dsfr.yml --strict

      - name: Verify DSFR theme in build
        run: |
          echo "=== Vérification DSFR ==="
          if grep -q "writer-html5" site/index.html; then
            echo "❌ ERREUR: HTML contient ReadTheDocs au lieu de DSFR!"
            head -20 site/index.html
            exit 1
          elif grep -q "data-fr-scheme" site/index.html; then
            echo "✅ OK: HTML contient DSFR"
            head -5 site/index.html
          else
            echo "⚠️  WARNING: Thème indéterminé"
            head -20 site/index.html
            exit 1
          fi

      - name: Install WeasyPrint system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libpango-1.0-0 \
            libpangoft2-1.0-0 \
            libpangocairo-1.0-0 \
            libcairo2 \
            libffi-dev \
            libgdk-pixbuf2.0-0 \
            libharfbuzz-dev \
            shared-mime-info

      - name: Generate PDF (DSFR)
        env:
          ENABLE_PDF_EXPORT: "1"
        run: |
          mkdir -p exports
          mkdocs build --config-file mkdocs-dsfr-pdf.yml --site-dir pdf-temp

      - name: Enrich PDF metadata
        run: python scripts/enrich_pdf_metadata.py exports/span-sg.pdf

      - name: Install qpdf and system dependencies for E2E
        run: |
          sudo apt-get update
          sudo apt-get install -y qpdf

      - name: Validate PDF
        run: |
          qpdf --check exports/span-sg.pdf
          ls -lh exports/span-sg.pdf
          echo "PDF size: $(du -h exports/span-sg.pdf | cut -f1)"

      - name: Set up Docker Buildx for E2E tests
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers for E2E tests
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile.mkdocs-test', 'requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Run E2E tests with reporting
        continue-on-error: true
        run: |
          chmod +x tests/e2e/ci_runner.sh
          ./tests/e2e/ci_runner.sh

      - name: Upload E2E report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-report
          path: tests/e2e/reports/e2e-report.html
          retention-days: 30

      - name: Install accessibility testing dependencies
        run: pip install -r requirements-accessibility.txt

      - name: Install Chrome and ChromeDriver for accessibility tests
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run accessibility tests (RGAA blocking - workaround search label)
        run: |
          python -m pytest tests/test_accessibility.py \
            -v \
            --html=accessibility-report.html \
            --self-contained-html

      - name: Upload accessibility report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: accessibility-report
          path: accessibility-report.html
          retention-days: 30

      - name: Upload PDF artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: exports-main
          path: exports/

      - name: Deploy production to GitHub Pages (Git push direct)
        run: |
          # Configuration Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone gh-pages
          git clone --depth=1 --branch=gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages-repo

          # Remplacer tout le contenu racine (production)
          cd gh-pages-repo
          # Garder draft/, supprimer le reste
          find . -mindepth 1 -maxdepth 1 ! -name 'draft' ! -name '.git' -exec rm -rf {} +
          # Copier nouveau contenu
          cp -r ../site/* .

          # Push
          git add .
          git commit -m "Deploy production from ${{ github.sha }}" || echo "No changes"
          git push origin gh-pages
